# Generated by Django 3.2.9 on 2021-11-21 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0003_alter_tool_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='id',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular listing', primary_key=True, serialize=False),
        ),
    ]
