# Generated by Django 3.2.9 on 2021-12-01 00:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0006_alter_tool_tool_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular tool', primary_key=True, serialize=False, unique=True),
        ),
    ]
