# Generated by Django 3.2.9 on 2021-11-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0002_auto_20211121_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='toolName',
            field=models.CharField(max_length=200),
        ),
    ]
