# Generated by Django 3.2.9 on 2021-11-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0005_tool_toolcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
