# Generated by Django 3.2.9 on 2021-11-21 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular listing', primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('lenderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular tool', primary_key=True, serialize=False, unique=True)),
                ('toolName', models.CharField(max_length=250)),
                ('toolBrand', models.CharField(blank=True, max_length=200, null=True)),
                ('toolModel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['toolName'],
            },
        ),
        migrations.CreateModel(
            name='Swaps',
            fields=[
                ('swaps_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular swap', primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('borrowerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listingId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolz_swap_app.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='toolId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolz_swap_app.tool'),
        ),
    ]
