# Generated by Django 3.2.9 on 2021-12-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0002_auto_20211208_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rented_tools',
            field=models.ManyToManyField(related_name='rented_tools', to='toolz_swap_app.Listings'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_places',
            field=models.ManyToManyField(related_name='saved_places', to='toolz_swap_app.Listings'),
        ),
    ]
