# Generated by Django 3.2.9 on 2021-12-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0005_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
