# Generated by Django 3.2.9 on 2021-12-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0006_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='size_sqkm',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='population',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='size_sqkm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tooltype',
            name='popularity',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
