# Generated by Django 3.2.9 on 2021-12-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0007_auto_20211211_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='size_sqkm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
