# Generated by Django 3.2.9 on 2021-12-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0009_auto_20211211_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rating_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
