# Generated by Django 3.2.9 on 2021-12-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0010_alter_listing_rating_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
