# Generated by Django 3.2.9 on 2021-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0013_alter_brand_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='item_image',
            field=models.ImageField(blank=True, default='post_images/CS113_concept_map.png', null=True, upload_to='post_images'),
        ),
    ]
