# Generated by Django 3.2.9 on 2021-12-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0015_alter_brand_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_image',
            field=models.ImageField(blank=True, default='listing_images/default.jpg', null=True, upload_to='listing_images'),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
