# Generated by Django 3.2.9 on 2021-12-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0011_user_rating_average'),
        ('toolz_swap_app', '0016_auto_20211214_0850'),
    ]

    operations = [
    ]
