# Generated by Django 3.2.9 on 2021-12-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0017_merge_20211215_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rating_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
