# Generated by Django 3.2.9 on 2021-12-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0017_merge_20211215_1930'),
        ('toolz_swap_app', '0017_merge_20211216_0832'),
    ]

    operations = [
    ]
