# Generated by Django 3.2.9 on 2021-12-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0018_auto_20211216_1946'),
        ('toolz_swap_app', '0019_auto_20211216_0923'),
    ]

    operations = [
    ]
