# Generated by Django 3.2.9 on 2021-12-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0019_auto_20211216_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='toolz_swap__name_99d212_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='toolz_swap__name_f368b1_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['title'], name='toolz_swap__title_c0ddac_idx'),
        ),
        migrations.AddIndex(
            model_name='listingreview',
            index=models.Index(fields=['rating'], name='toolz_swap__rating_d373c5_idx'),
        ),
        migrations.AddIndex(
            model_name='listingreview',
            index=models.Index(fields=['listing'], name='toolz_swap__listing_ba26ad_idx'),
        ),
        migrations.AddIndex(
            model_name='neighborhood',
            index=models.Index(fields=['name'], name='toolz_swap__name_35afc3_idx'),
        ),
        migrations.AddIndex(
            model_name='tooltype',
            index=models.Index(fields=['name'], name='toolz_swap__name_214609_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='toolz_swap__first_n_4aaf87_idx'),
        ),
    ]
