# Generated by Django 3.2.9 on 2021-12-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0020_merge_0018_auto_20211216_1946_0019_auto_20211216_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='item_image',
        ),
        migrations.AlterField(
            model_name='brand',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images'),
        ),
    ]
