# Generated by Django 3.2.9 on 2021-12-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0021_auto_20211217_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingrequest',
            name='renting_start',
            field=models.DateTimeField(),
        ),
    ]
