# Generated by Django 3.2.9 on 2021-12-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolz_swap_app', '0022_alter_listingrequest_renting_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
